### ISSUE TITLE
apt-get install ncbi-blast+ 安装后后，./scripts/run_mf.sh运行代码PsiBlast出现问题

### ISSUE THREAD

**Issue by codeinging** [yourh/DeepGraphGO#18]
[I 231011 06:51:46 psiblast_utils:29] Using exists blast output file results/mf-valid-ppi-blast-out.xml
Parsing PsiBlast results:  90%|█████████████▍ | 440/490 [00:10<00:01, 42.50it/s]
Traceback (most recent call last):
  File "/data1/experiment_code/sunyundong/bioinformation/DeepGraphGO/main.py", line 92, in <module>
    main()
  File "/home/visitor/anaconda3/envs/DeepGraphGO/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/visitor/anaconda3/envs/DeepGraphGO/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/visitor/anaconda3/envs/DeepGraphGO/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/visitor/anaconda3/envs/DeepGraphGO/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/data1/experiment_code/sunyundong/bioinformation/DeepGraphGO/main.py", line 60, in main
    *_, valid_ppi, valid_y = get_homo_ppi_idx(valid_pid_list, data_cnf['valid']['fasta_file'],
  File "/data1/experiment_code/sunyundong/bioinformation/DeepGraphGO/deepgraphgo/data_utils.py", line 126, in get_homo_ppi_idx
    blast_sim = blast(net_blastdb, pid_list, fasta_file, blast_output_path)
  File "/data1/experiment_code/sunyundong/bioinformation/DeepGraphGO/deepgraphgo/psiblast_utils.py", line 44, in blast
    return psiblast(*args, **kwargs, num_iterations=1)
  File "/data1/experiment_code/sunyundong/bioinformation/DeepGraphGO/deepgraphgo/psiblast_utils.py", line 32, in psiblast
    for pid, rec in zip(tqdm(pid_list, desc='Parsing PsiBlast results'), NCBIXML.parse(fp)):
  File "/home/visitor/anaconda3/envs/DeepGraphGO/lib/python3.8/site-packages/Bio/Blast/NCBIXML.py", line 827, in parse
    expat_parser.Parse(NULL, True)  # End of XML record
xml.parsers.expat.ExpatError: no element found: line 2398046, column 0

**Comment by song2000012138** [comment]
conda install -c bioconda blast  
使用conda安装blast

**Comment by yourh** [comment]
把p应该是psiblast没跑完，删掉文件重新跑一次试试看

**Comment by yourh** [comment]
应该是psiblast没跑成功，删掉psiblast生成的文件重新跑一次试试看
