### ISSUE TITLE
Regarding the decompression of data

### ISSUE THREAD

**Issue by xmcs111** [yourh/DeepGraphGO#2]
I am a newbie in graph neural network. Regarding the decompression of data, after using your command dtrx -f data.zip, an error is reported. I would like to ask whether this command can be used under pycharm of windows. If not, how to extract the data . In addition, when the main time is executed, AttributeError: module'dgl' has no attribute'NodeFlow' is reported. I don't quite understand how to execute this code, please answer

**Comment by xmcs111** [comment]
TypeError: expected str, bytes or os.PathLike object, not NoneType

**Comment by yourh** [comment]
The commands are used for Linux, because sometimes unzip doesn't work for the multi-part archive. In Windows, just extract it directly.
Please check the version of dgl you used.

**Comment by xmcs111** [comment]
The DGL I use is the version in your document, and then the path error is reported, as above

**Comment by yourh** [comment]
Please check the document [https://docs.dgl.ai/en/0.4.x/api/python/nodeflow.html]( https://docs.dgl.ai/en/0.4.x/api/python/nodeflow.html) . Obviously,  dgl of this version has "dgl.NodeFlow".

**Comment by xmcs111** [comment]
Hello, the following error is reported when executing the main program
```
Using backend: pytorch
Traceback (most recent call last):
  File "D:/Users/.../PycharmProjects/deepgrago210721/main.py", line 92, in <module>
    main()
  File "D:\Users\...\PycharmProjects\deepgrago210721\venv\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "D:\Users\...\PycharmProjects\deepgrago210721\venv\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "D:\Users\...\PycharmProjects\deepgrago210721\venv\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "D:\Users\...\PycharmProjects\deepgrago210721\venv\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "D:/Users/.../PycharmProjects/deepgrago210721/main.py", line 31, in main
    data_cnf, model_cnf = yaml.load(Path(data_cnf)), yaml.load(Path(model_cnf))
  File "D:\Users\...\AppData\Local\Programs\Python\Python38\lib\pathlib.py", line 1038, in __new__
    self = cls._from_parts(args, init=False)
  File "D:\Users\...\AppData\Local\Programs\Python\Python38\lib\pathlib.py", line 679, in _from_parts
    drv, root, parts = self._parse_args(args)
  File "D:\Users\...\AppData\Local\Programs\Python\Python38\lib\pathlib.py", line 663, in _parse_args
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

**Comment by yourh** [comment]
Which command did you run?

**Comment by xmcs111** [comment]
python preprocessing.py data/ppi_mat.npz data/ppi_dgl_top_100
Run the preprocessing script run after:``` File "preprocessing.py", line 34 ppi_net_mat = (mat_:=ssp.load_npz(ppi_net_mat_path)) + ssp.eye(mat_.shape[0], format='csr') ^ SyntaxError: invalid syntax

**Comment by yourh** [comment]
Please use the version of python in README.
